# Generated by Django 4.1 on 2022-09-09 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artilce_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=200)),
                ('article_code', models.CharField(max_length=200)),
                ('article_size', models.CharField(max_length=50)),
                ('article_colour', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='artilce_sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_date', models.DateField()),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_name', models.TextField(max_length=100)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_app.artilce_details')),
            ],
        ),
    ]
