# Generated by Django 4.1 on 2022-09-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artilce_details',
            name='article_image',
            field=models.ImageField(default='NA', upload_to='products/'),
        ),
    ]
